version: '3'
services:
  api:
    container_name: hr_api
    build: .
    ports:
        - "5005:5000"
    depends_on:
        - hr_database
  hr_database:
    container_name: hr_database
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=_ABCabc123
      - POSTGRES_DB=humanresource
    #volumes:
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql